version: "3"
services:
  openai-proxy:
    build: .
    container_name: openai-proxy
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_TOKEN=sk-1234567890abcdef
      - AGENT_ROLL_INTERVAL=60000
